name: Docker Image CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      if: github.event.schedule != '0 0 * * *'
      run: |
           docker build . -t registry.jonasg.be/govaertsjonas/discord-webhook:stable &&
           docker push registry.jonasg.be/govaertsjonas/discord-webhook:stable
    - name: Build the Docker image
      if: github.event.schedule == '0 0 * * *'
      run: |
           docker build . -t registry.jonasg.be/govaertsjonas/discord-webhook:nightly &&
           docker push registry.jonasg.be/govaertsjonas/discord-webhook:nightly
